import type { Metadata } from 'next';
import Link from 'next/link';
import { site } from '@/config/site';

export const metadata: Metadata = {
  title: 'Terms of Service — GoAnyway Event Plan Tool',
  description: 'GoAnyway terms of service. Events are live-sourced; verify before attending. Plans are AI-generated, not a guarantee. Payment is $9 and all sales are final.',
  openGraph: {
    title: 'Terms of Service — GoAnyway Event Plan Tool',
    description: 'GoAnyway terms of service. Events are live-sourced; verify before attending. Plans are AI-generated, not a guarantee. Payment is  and all sales are final.',
    url: `${site.url}/terms`,
    siteName: site.name,
  },
};

export default function TermsPage() {
  return (
    <main className="min-h-screen px-6 py-16">
      <div className="mx-auto max-w-xl space-y-10">
        <div>
          <Link
            href="/"
            className="text-muted hover:text-text font-mono text-xs tracking-widest uppercase"
          >
            ← Back
          </Link>
          <h1 className="font-heading mt-6 text-3xl font-bold">Terms of Service</h1>
          <p className="text-muted mt-2 font-mono text-xs">Last updated: June 2025</p>
        </div>

        <section className="space-y-4 text-base">
          <h2 className="font-heading text-lg font-bold">What GoAnyway is</h2>
          <p>
            GoAnyway is a tool that generates a plan — a real event, a briefing on what to expect,
            and a first-hour script — for showing up to a social group for the first time. The plan
            is AI-generated based on your inputs. It is a starting point, not a guarantee.
          </p>
        </section>

        <section className="space-y-4 text-base">
          <h2 className="font-heading text-lg font-bold">Payment</h2>
          <p>
            The comfort stat and script are unlocked with a one-time $9 payment via Stripe. All
            sales are final. We do not offer refunds. If you have a problem with your plan, email{' '}
            <a
              href="mailto:luke@modrynstudio.com"
              className="text-accent underline underline-offset-4"
            >
              luke@modrynstudio.com
            </a>{' '}
            and we will sort it out.
          </p>
        </section>

        <section className="space-y-4 text-base">
          <h2 className="font-heading text-lg font-bold">AI-generated content</h2>
          <p>
            Events, briefings, and scripts are generated by AI. Event details (date, time, venue,
            URL) are sourced from Meetup, Eventbrite, and Lu.ma via a live search at the time you
            submit your form. We cannot guarantee that event details are accurate or that events
            have not changed or been cancelled. Verify with the event organizer before you go.
          </p>
          <p>
            The comfort stat (percentage) is a model-generated estimate based on general patterns
            for your activity type. It is not sourced from a survey or study.
          </p>
        </section>

        <section className="space-y-4 text-base">
          <h2 className="font-heading text-lg font-bold">No guarantee of outcome</h2>
          <p>
            GoAnyway gets you to the door. What happens after is up to you. We make no guarantees
            about social outcomes, friendships, or whether you will enjoy the event.
          </p>
        </section>

        <section className="space-y-4 text-base">
          <h2 className="font-heading text-lg font-bold">SMS</h2>
          <p>
            Opting in to SMS sends two messages: one reminder before the event, one follow-up after.
            Message and data rates may apply. Reply STOP at any time to opt out.
          </p>
        </section>

        <section className="space-y-4 text-base">
          <h2 className="font-heading text-lg font-bold">Contact</h2>
          <p>
            Questions?{' '}
            <a
              href="mailto:luke@modrynstudio.com"
              className="text-accent underline underline-offset-4"
            >
              luke@modrynstudio.com
            </a>
          </p>
        </section>
      </div>
    </main>
  );
}
